### ISSUE TITLE
Write sig service

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/sig-service#1]
It should:
- On start, clone the remote repo: git@github.com:commercialhaskell/sig-archive.git It will need push access to the repo.
- Accept uploads of `.asc` files targeted at a specific package-version uploaded by `sig-tool`.
- Serve up an archive of the whole archive to be downloaded by `sig-tool`.
- Have some page in `/` to greet people curious enough to look at it, linking to `sig-archive` and/or `sig-service`.
- It should pull from the git repo maybe every 10 minutes or something.

The uploaded `.asc` may do some additional things like:
- Check whether the package exists on Hackage and reject it if not. For now we can assume people may want to upload their signature before uploading their package, so I propose to hold off on this.
- If, for example, more than 50 signatures are uploaded by a person in an hour, flag this up as potential spam and reject the request saying so.

The serving of the archive could be:
- A .tar.gz which is unpacked and then the YAML files read in.
- Alternatively be a big JSON value. 

The former has better debugging/user investigation potential, the latter is a little more direct. At any rate, versioning the API might be useful. And the archive will be downloaded quite regularly by the tool, possibly on every `install` invocation, so it ought to be gzipped anyway.

Additionally, the former option has the advantage of re-using the same loading code in both the server and the client.

When a `.asc` is uploaded, the service should:
1. Copy the file into the local copy of the repo.
2. Commit the change.
3. Pull --rebase.
4. Push to the github repo. If it fails to push, just repeat from step 3.
5. Re-read in the archive a-fresh.

The `/` placeholder page may optionally list some data about percentage of Hackage packages signed or something.

**Comment by ndmitchell** [comment]
Hmm, this seems quite permissions/git heavy. I would have expected an HTTP endpoint where you just give a signature and package version on Hackage, and it validates it all and writes it to a database.

**Comment by chrisdone** [comment]
So this `sig-service` is an HTTP endpoint (either PUT or a POST, maybe even a web page too? For those without `sig-tool`) where you give it a signature and a package version, but rather than writing it to a database, it writes it to the publicly readable and writable (by PR's) github repo [`sig-archive`](https://github.com/commercialhaskell/sig-archive). Objections?

**Comment by chrisdone** [comment]
Following up with our thought process: The advantages we considered for just using a plain old github repo was (1) transparency, (2) to make a small point of showing that it doesn't matter how secure the service is that _stores_ the signatures, (3) make it feel more open to contribution, like stackage (the build-constraints.yaml).

**Comment by ndmitchell** [comment]
Ah, I think I got the wrong end of the stick. I thought people would be running sig service locally, but in fact they'll just be hitting it over http, which is what I was asking for anyway.

**Comment by chrisdone** [comment]
Okay, cool. I'll clarify this in the README on this repo. Thanks!

**Comment by dysinger** [comment]
Most of this is done. It also additionally leases the ssh key from Vault/Consul.  The part about checking for spam & non-existing packages isn't implemented.

**Comment by dysinger** [comment]
also since we initially started this effort, we've added the ability to sign all your hackage package & version combos.  That would most certainly trip the 50 signatures alarm for active library maintainers.
